### ISSUE TITLE
请问php这些文件应该放置到哪里？

### ISSUE THREAD

**Issue by jadelike-wine** [MrZhang1899/WxWork_Push#1]
您好，请问php这些文件应该放置到哪里？我是Debian 10，我放到var/www/html之下，发现没用

**Comment by cn0068** [comment]
> 您好，请问php这些文件应该放置到哪里？我是Debian 10，我放到var/www/html之下，发现没用

放到你网站目录下啊，如果是根目录，就访问：http://你的域名/?msg=推送测试
