### ISSUE TITLE
推送天气不显示地点

### ISSUE THREAD

**Issue by cn0068** [MrZhang1899/WxWork_Push#2]
运行：http://192.168.50.109:6512/wxpush/001/?type=weather&loc=beijing

{"errcode":0,"errmsg":"ok","invaliduser":"","msgid":"mrVtVXE39it1tWVvd57npP-xd0j1YhAPY6uEqf2TYiIdygvRmiXkNtVWHyps47RHz80EEiBKWcyjtoqVfN9N9g"}
企业微信能收到推送的消息：
-30度
更新时间  
温度

地点并未显示出来

请问是什么原因？

**Comment by KurococLiu** [comment]
https://github.com/6isixi/WxWork_Push
可以试试我这个，修复了这个bug的，你也可以直接复制我这个库里面weather.php的内容到你服务器上的weather.php上，同时支持Vercel部署，只需要修改企业微信应用的配置即可

**Comment by cn0068** [comment]
> https://github.com/6isixi/WxWork_Push
> 可以试试我这个，修复了这个bug的，你也可以直接复制我这个库里面weather.php的内容到你服务器上的weather.php上，同时支持Vercel部署，只需要修改企业微信应用的配置即可

谢谢，问题解决！

**Comment by KurococLiu** [comment]
> > https://github.com/6isixi/WxWork_Push
> > 这个可以训练我的这个问题，修复了可以这个bug的，你也直接复制我库里面weather.php的内容到你服务器上的weather.php上，同时支持Vercel开发，只需要修改企业微信应用的配置
> 
> 谢谢，问题解决！

没事的hhh

**Comment by MrZhang1899** [comment]
已修复更新此问题，感谢反馈！
